    #ifndef REDUCE_H_ADDED__
    #define REDUCE_H_ADDED__
    /*  reduce.h  apply reduce function to arglist
    v1.00 by FrozenVoid: License:Affero GPL 3.0 -> www.gnu.org/licenses/agpl-3.0.en.html

    Macro: reducel(func,accum,args...) -> 
    f(accum,arg1),f(accum,arg2),f(accum,arg3)...

    example:
    int v=0;
    #define f(x,y) ({x+=y;})//returning x
    printf("%d",reduce(f,v,1,2,3,4,5));//last elem returns f(x,5)
    result: 15

    */
    #include "vapply.h"


    #define reduce(func,op_accum,args...) (vapply_merge(reduce,vapply_numargs(args))(func,op_accum,args))


    #define reduce0(f,op) op
    #define reduce1(f,op,a) f(op,a)
    #define reduce2(f,op,a,a2) f(op,a),f(op,a2)
    #define reduce3(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce4(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce5(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce6(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce7(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce8(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce9(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce10(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce11(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce12(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce13(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce14(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce15(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce16(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce17(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce18(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce19(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce20(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce21(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce22(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce23(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce24(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce25(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce26(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce27(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce28(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce29(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce30(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce31(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce32(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce33(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce34(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce35(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce36(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce37(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce38(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce39(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce40(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce41(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce42(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce43(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce44(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce45(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce46(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce47(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce48(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce49(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce50(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce51(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce52(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce53(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce54(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce55(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce56(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce57(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce58(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce59(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce60(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce61(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce62(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce63(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce64(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce65(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce66(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce67(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce68(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce69(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce70(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce71(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce72(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce73(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce74(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce75(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce76(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce77(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce78(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce79(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce80(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce81(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce82(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce83(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce84(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce85(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce86(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce87(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce88(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce89(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce90(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce91(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce92(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce93(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce94(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce95(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce96(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce97(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce98(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce99(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce100(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce101(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce102(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce103(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce104(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce105(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce106(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce107(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce108(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce109(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce110(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce111(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce112(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce113(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce114(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce115(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce116(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce117(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce118(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce119(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce120(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce121(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce122(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce123(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce124(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce125(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce126(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce127(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce128(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce129(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce130(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce131(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce132(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce133(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce134(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce135(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce136(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce137(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce138(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce139(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce140(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce141(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce142(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce143(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce144(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce145(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce146(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce147(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce148(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce149(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce150(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce151(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce152(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce153(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce154(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce155(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce156(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce157(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce158(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce159(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce160(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce161(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce162(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce163(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce164(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce165(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce166(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce167(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce168(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce169(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce170(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce171(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce172(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce173(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce174(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce175(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce176(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce177(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce178(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce179(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce180(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce181(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce182(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce183(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce184(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce185(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce186(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce187(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce188(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce189(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce190(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce191(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce192(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce193(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce194(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce195(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce196(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce197(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce198(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce199(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce200(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce201(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce202(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce203(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce204(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce205(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce206(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce207(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce208(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce209(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce210(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce211(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce212(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce213(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce214(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce215(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce216(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce217(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce218(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce219(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce220(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce221(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce222(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce223(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce224(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce225(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce226(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce227(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce228(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce229(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce230(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce231(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce232(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce233(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce234(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce235(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce236(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce237(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce238(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce239(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce240(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce241(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce242(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce243(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce244(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce245(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce246(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce247(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce248(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce249(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce250(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce251(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce252(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce253(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce254(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce255(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce256(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce257(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce258(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce259(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce260(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce261(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce262(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce263(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce264(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce265(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce266(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce267(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce268(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce269(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 

    #define reduce270(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce271(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce272(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce273(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce274(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce275(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce276(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce277(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce278(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce279(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce280(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce281(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce282(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce283(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce284(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce285(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce286(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce287(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce288(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce289(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce290(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce291(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce292(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce293(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce294(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce295(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce296(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce297(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce298(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 
    #define reduce299(f,op,a,args...) f(op,a),vapply_merge(reduce,vapply_numargs(args))(f,op,args) 




    #endif

