    #ifndef VAPPLY_H_ADDED__
    #define VAPPLY_H_ADDED__
    #include "fapply.h"//https://www.reddit.com/r/frozenvoid/wiki/void2/fapply_h
    #include "argdetect.h"//https://www.reddit.com/r/frozenvoid/wiki/void2/argdetect_h

    /*  vapply.h  vapply func/macro and operator to arglist
    v1.02 by FrozenVoid: License:Affero GPL 3.0 -> www.gnu.org/licenses/agpl-3.0.en.html
    vapply - variadic op() apply:Core Function 
    Macro: 
    vapply: f= applied to each arg, op=wraps next vapply
    vapply(f,op,arg1,args...) -> f(arg1) op(vapply(args))
    #define op_add(a...) +a
    vapply(func,op_add,100,1,3,4);-> func(100)+func(1)+func(3)+func(4)


    vapply(f,op)== apply(f) == f(), minargs=0 maxargs=256
    Application to arglist:   
    apply: f=applies to each arg, separated by comma
    apply(f,arg1,args...) -> f(arg1),f(arg2),apply(args)   
    Operator Apply:
    opapply(op,args) => arg1 op arg2 op arg3 ...
    ex: opapply(+,1,2,3) -> 1+2+3
    opapply("","these","strings","will be","merged") -> 
    "these" "" "strings" "" "will be" "" "merged"  
    (C constant string concatenation)

fapply expansion ref:
#define fa1(f1,f2,op1,f3,f4,op2,args...) f1(f2(args))
#define fa2(f1,op1,f2,op2,f3,op3,f4,op4,args...) f1(f2(args)) op1 f3(f4(f1,f2,op1,f3,f4,op2,args)) op2


    */



    #define vapply_merge1(a,b) a##b
    #define vapply_merge(a,b) vapply_merge1(a,b)
    #define vapplyfunc(f,op,args...) vapply_merge(vapply,vapply_numargs(args))(f,op,args)


    #define vapply_id(...) __VA_ARGS__
    #define vapply_ig(...)
    #define vapply(f,op,...) vapplyfunc(f,op,__VA_ARGS__)
  #define vapply_first(arg,rest...) arg
#define vapply_rest(arg,rest...) rest
 #define vapply_op1(n) n
 #define vapply_op0(n) 
 #define fapplyfunc_f(f,t,a) fapplyfunc(f,t,a)
#define vapply_forward_args(f,t,args...) fapplyfunc_f(f,t,(vapply_rest(args)))
    #define vapply_next(f,t,a) vapply_first(vapply_id t)(vapply_first a) vapply_merge(vapply_op,oneplusargs(vapply_rest a))(vapply_rest t)  vapply_forward_args(f,t,a)
    #define vapplyx(f,op,args...) fapply(vapply_next,(f,op),(args))
    #define vapply_comma(...) ,__VA_ARGS__ 
	#define apply(f,args...) vapply(f,vapply_comma,args)
    #define opapply(op,args...)  vapply(vapply_id,op vapply_id,args)

#define apply_ig(...) 
#define apply_id(a...) a
#define apply_empty 

#define apply_comma1() ,
#define apply_comma0() 
#define apply_comma apply_comma1()

#define apply_next(t,a) apply_first t(apply_first a) vapply_merge(apply_comma,twoplusargs a)()  vapply_merge(applyfunc,)(f,t,apply_rest a) 
#define applyz(f,args...) fapply(apply_next,(f,apply_comma),(args)) 
   

    //shifted num         x, 4, 3, 2, 1,=1
    //                    x.y. 4. 3. 2  =2
    //           vapplyn[n=argcount] (f,args)      
    #define vapply_count1(_0,_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67,_68,_69,_70,_71,_72,_73,_74,_75,_76,_77,_78,_79,_80,_81,_82,_83,_84,_85,_86,_87,_88,_89,_90,_91,_92,_93,_94,_95,_96,_97,_98,_99,_100,_101,_102,_103,_104,_105,_106,_107,_108,_109,_110,_111,_112,_113,_114,_115,_116,_117,_118,_119,_120,_121,_122,_123,_124,_125,_126,_127,_128,_129,_130,_131,_132,_133,_134,_135,_136,_137,_138,_139,_140,_141,_142,_143,_144,_145,_146,_147,_148,_149,_150,_151,_152,_153,_154,_155,_156,_157,_158,_159,_160,_161,_162,_163,_164,_165,_166,_167,_168,_169,_170,_171,_172,_173,_174,_175,_176,_177,_178,_179,_180,_181,_182,_183,_184,_185,_186,_187,_188,_189,_190,_191,_192,_193,_194,_195,_196,_197,_198,_199,_200,_201,_202,_203,_204,_205,_206,_207,_208,_209,_210,_211,_212,_213,_214,_215,_216,_217,_218,_219,_220,_221,_222,_223,_224,_225,_226,_227,_228,_229,_230,_231,_232,_233,_234,_235,_236,_237,_238,_239,_240,_241,_242,_243,_244,_245,_246,_247,_248,_249,_250,_251,_252,_253,_254,_255,N,...) N
    #define vapply_count(args...) vapply_count1(args) 
    //  args push>>> n. 3,2,1 :: :args:<numbers> 
    #define vapply_numargs(args...) vapply_count(args,256,255,254,253,252,251,250,249,248,247,246,245,244,243,242,241,240,239,238,237,236,235,234,233,232,231,230,229,228,227,226,225,224,223,222,221,220,219,218,217,216,215,214,213,212,211,210,209,208,207,206,205,204,203,202,201,200,199,198,197,196,195,194,193,192,191,190,189,188,187,186,185,184,183,182,181,180,179,178,177,176,175,174,173,172,171,170,169,168,167,166,165,164,163,162,161,160,159,158,157,156,155,154,153,152,151,150,149,148,147,146,145,144,143,142,141,140,139,138,137,136,135,134,133,132,131,130,129,128,127,126,125,124,123,122,121,120,119,118,117,116,115,114,113,112,111,110,109,108,107,106,105,104,103,102,101,100,99,98,97,96,95,94,93,92,91,90,89,88,87,86,85,84,83,82,81,80,79,78,77,76,75,74,73,72,71,70,69,68,67,66,65,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1)

    #define vapply0(f,op) f()
    #define vapply1(f,op,a) f(a)
    #define vapply2(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply3(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply4(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply5(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply6(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply7(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply8(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply9(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply10(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply11(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply12(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply13(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply14(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply15(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply16(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply17(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply18(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply19(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply20(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply21(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply22(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply23(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply24(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply25(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply26(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply27(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply28(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply29(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply30(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply31(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply32(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply33(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply34(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply35(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply36(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply37(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply38(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply39(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply40(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply41(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply42(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply43(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply44(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply45(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply46(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply47(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply48(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply49(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply50(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply51(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply52(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply53(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply54(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply55(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply56(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply57(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply58(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply59(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply60(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply61(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply62(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply63(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply64(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply65(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply66(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply67(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply68(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply69(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply70(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply71(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply72(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply73(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply74(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply75(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply76(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply77(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply78(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply79(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply80(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply81(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply82(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply83(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply84(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply85(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply86(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply87(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply88(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply89(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply90(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply91(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply92(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply93(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply94(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply95(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply96(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply97(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply98(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply99(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply100(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply101(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply102(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply103(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply104(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply105(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply106(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply107(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply108(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply109(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply110(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply111(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply112(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply113(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply114(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply115(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply116(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply117(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply118(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply119(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply120(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply121(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply122(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply123(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply124(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply125(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply126(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply127(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply128(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply129(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply130(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply131(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply132(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply133(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply134(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply135(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply136(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply137(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply138(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply139(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply140(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply141(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply142(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply143(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply144(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply145(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply146(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply147(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply148(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply149(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply150(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply151(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply152(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply153(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply154(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply155(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply156(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply157(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply158(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply159(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply160(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply161(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply162(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply163(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply164(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply165(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply166(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply167(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply168(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply169(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply170(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply171(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply172(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply173(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply174(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply175(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply176(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply177(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply178(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply179(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply180(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply181(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply182(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply183(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply184(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply185(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply186(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply187(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply188(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply189(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply190(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply191(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply192(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply193(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply194(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply195(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply196(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply197(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply198(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply199(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply200(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply201(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply202(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply203(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply204(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply205(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply206(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply207(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply208(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply209(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply210(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply211(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply212(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply213(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply214(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply215(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply216(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply217(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply218(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply219(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply220(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply221(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply222(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply223(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply224(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply225(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply226(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply227(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply228(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply229(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply230(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply231(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply232(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply233(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply234(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply235(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply236(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply237(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply238(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply239(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply240(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply241(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply242(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply243(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply244(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply245(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply246(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply247(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply248(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply249(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply250(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply251(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply252(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply253(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply254(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply255(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply256(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply257(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply258(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply259(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply260(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply261(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply262(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply263(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply264(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply265(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply266(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply267(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply268(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply269(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))

    #define vapply270(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply271(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply272(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply273(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply274(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply275(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply276(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply277(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply278(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply279(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply280(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply281(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply282(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply283(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply284(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply285(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply286(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply287(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply288(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply289(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply290(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply291(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply292(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply293(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply294(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply295(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply296(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply297(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply298(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))
    #define vapply299(f,op,a,args...) f(a) op(vapply_merge(vapply,vapply_numargs(args))(f,op,args))










    #endif
